type iconNameType =
    'caret--down'
  | 'caret--up'
  | 'checkbox'
  | 'checkbox--checked'
  | 'cloud--upload'
  | 'continue'
  | 'continue--filled'
  | 'creative--commons-by'
  | 'creative--commons-from'
  | 'debug'
  | 'erase'
  | 'keyboard'
  | 'launch'
  | 'logo--discord'
  | 'logo--github'
  | 'pause'
  | 'pause--filled'
  | 'play'
  | 'play--filled'
  | 'redo'
  | 'repeat'
  | 'stop'
  | 'stop--filled'
  | 'transform--code'
  | 'undo'
  | 'view'
  | 'view--off'

export {
  type iconNameType
}
