type iconNameType =
    'add'
  | 'caret--down'
  | 'caret--up'
  | 'chat'
  | 'checkbox'
  | 'checkbox--checked'
  | 'close--outline'
  | 'cloud--upload'
  | 'continue'
  | 'continue--filled'
  | 'creative-commons--by'
  | 'creative-commons--zero'
  | 'debug'
  | 'help'
  | 'keyboard'
  | 'launch'
  | 'logo--discord'
  | 'logo--github'
  | 'maximize'
  | 'minimize'
  | 'orfeo'
  | 'pause'
  | 'pause--filled'
  | 'play'
  | 'play--filled'
  | 'redo'
  | 'repeat'
  | 'search'
  | 'stop'
  | 'stop--filled'
  | 'subtract'
  | 'trash-can'
  | 'undo'
  | 'view'
  | 'view--off'

export {
  type iconNameType
}
